from selenium import webdriver
import time
driver=webdriver.Chrome("C:\Program Files (x86)\Google\Chrome\Application\chromedriver.exe")
driver.get("https://www.baidu.com")
#driver.find_element_by_id("kw").send_keys("selenium")
#driver.find_element_by_id("su").click()
time.sleep(2)
driver.find_element_by_css_selector("#u1 > a.lb").click()
time.sleep(2)
driver.find_element_by_id("TANGRAM__PSP_10__userName").send_keys("刘灿的文库")
time.sleep(0.5)
driver.find_element_by_id("TANGRAM__PSP_10__password").send_keys("liuCAN80")
time.sleep(1)
driver.find_element_by_id("TANGRAM__PSP_10__memberPass").click()
time.sleep(1)
verifycode=input("请输入验证码:\n")
driver.find_element_by_id("TANGRAM__PSP_10__verifyCode").send_keys(verifycode)
driver.find_element_by_id("TANGRAM__PSP_10__submit").click()
driver.maximize_window()
print("hello")